2018-05-07 16:59:51,472 INFO: Microblog startup [in /Users/vanyroca/Desktop/BrunoCompSci/app/__init__.py:51]
2018-05-07 17:06:45,279 ERROR: Exception on /unfollow/Bruno [GET] [in /Library/Python/2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Python/2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/vanyroca/Desktop/BrunoCompSci/app/routes.py", line 131, in unfollow
    user = User.qurey.filter_by(username=username).first()
AttributeError: type object 'User' has no attribute 'qurey'
